name: CI_IBM

on: [push] #ação 

jobs:
  builds:
    runs-on: ubuntu-20.04 #maquina
    steps: 
    - name: Roda um script shell
      run: echo "Olá git actions"

  teste:
    runs-on: ubuntu-20.04 #maquina
    needs: build
    steps: 
    - name: Roda um script shell
      run: echo "Olá git actions teste"