name: CI_IBM

on: [push] #ação 

jobs:
  builds:
    runs-on: ubuntu-20.04 #maquina

    steps: 
    - name: Roda um script shell
      run: echo "Olá git actions"  # script

  teste:
    runs-on: ubuntu-20.04 #maquina
    needs: builds
    steps: 
    - name: Roda um script shell
      run: echo "Olá git actions teste"




#       name: CI_IBM

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-20.04

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'adopt'
#       - name: Build with Maven
#         run: mvn package -Dmaven.test.skip

#   test:
#     runs-on: ubuntu-20.04
#     needs: build
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'adopt'
#       - name: Rodando test
#         run: mvn test